# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'GRPCTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GRPCTest
  pod 'GRPCTest', :path => 'GRPCTest.podspec'
  target 'GRPCTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GRPCTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
